config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  resources :categories, only: [:index, :show], param: :slug

  resources :cart, only: [:index]
  resources :users, only: [:new, :create, :update, :edit]
  get "/lender_dashboard", to: "users#lender_dashboard"
  get "/borrower_dashboard", to: "users#borrower_dashboard"
  put '/become_borrower', to: "users#become_borrower"
  put '/become_lender', to: "users#become_lender"

  resources :lenders, only: [:new], param: :slug
  resources :borrowers, only: [:new], param: :slug

  get '/login', to: "session#new"
  post '/login', to: "session#create"
  delete '/logout', to: "session#destroy"
  post '/checkout', to: "loans#create"

  resources :borrower_projects, only: [:new, :create]
  resources :projects, only: [:index]

  namespace :admin do
    resources :dashboard, only: [:index, :show]
    resources :projects, only: [:update]
    resources :categories, only: [:index, :new, :create]
  end

  namespace :users, path: ":user", as: :user do
    resources :projects, only: [:show]
    resources :cart_projects, only: [:create, :new, :update, :destroy]
  end

  get '*unmatched_route', to: 'application#not_found'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    @projects = Project.all
  end

  def show
    @admin = current_user
    @projects = Project.where(status: "Pending")
  end
end

app/views/admin/dashboard/index.html.erb
<h1>Admin Dashboard</h1>

<%= link_to "Categories", admin_categories_path, class: "waves-effect waves-light btn custom-blue" %>

<h3>Current Projects</h3>

<table id='projects' class="highlight">
  <thead>
    <tr>
      <th data-field="id">Project</th>
      <th data-field="name">Date Created</th>
      <th data-field="current_status">Current Status</th>
      <th data-field="adjust_status">Adjust Status</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, user_project_path(user: project.user.slug, id: project.slug) %></td>
        <td><%= project.created_at.strftime("%B %d, %Y") %></td>
        <td><%= project.status unless project.status.nil? %></td>
        <td>
          <% if project.status == "Pending" %>
            <%= link_to "Mark As Approved", admin_project_path(:id => project.id, :status => "Active"), method: :put  %><br>
            <%= link_to "Cancel", admin_project_path(:id => project.id, :status => "Cancelled"), method: :put  %>
          <% elsif project.status == "Active" %>
            <%= link_to "Mark as Completed", admin_project_path(:id => project.id, :status => "Completed"), method: :put  %><br>
            <%= link_to "Cancel", admin_project_path(:id => project.id, :status => "Cancelled"), method: :put  %>
          <% else %>
            Project Inactive
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/dashboard/show.html.erb
<div id="profile">
  <h4><%= current_user.username %>'s Admin Profile</h4>
  <div class="col s4">
    <a class="image-link"><img class="max-width" src="<%= current_user.image.url(:original) %>"></a>
  </div>
  <p>
    <strong>First name: </strong><%= current_user.first_name %>
  </p>
  <p>
    <strong>Last name: </strong><%= current_user.last_name %>
  </p>
  <p>
    <strong>Username: </strong><%= current_user.username %>
  </p>
  <p>
    <strong>Bio: </strong><%= current_user.bio %>
  </p>

  <div id='user-<%= current_user.id %>-button' class="waves-effect waves-light btn blue">
    <%= button_to "Edit Profile", edit_user_path(current_user), method: :get %>
  </div>

  <div class="projects">
    <h4>Pending Projects</h4>

    <table id='projects' class="highlight">
      <thead>
        <tr>
          <th data-field="id">Project</th>
          <th data-field="name">Date Created</th>
          <th data-field="current_status">Current Status</th>
          <th data-field="adjust_status">Adjust Status</th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= link_to project.title, admin_project_path(id: project.slug) %></td>
            <td><%= project.created_at.strftime("%B %d, %Y") %></td>
            <td><%= project.status unless project.status.nil? %></td>

            <td>
              <% if project.status == "Pending" %>
                <%= link_to "Mark As Approved", admin_project_path(:id => project.id, :status => "Active", :source => "Profile"), method: :put  %><br>
                <%= link_to "Cancel", admin_project_path(:id => project.id, :status => "Cancelled", :source => "Profile"), method: :put  %>
              <% elsif project.status == "Active" %>
                <%= link_to "Mark as Completed", admin_project_path(:id => project.id, :status => "Completed", :source => "Profile"), method: :put  %><br>
                <%= link_to "Cancel", admin_project_path(:id => project.id, :status => "Cancelled", :source => "Profile"), method: :put  %>
              <% else %>
                Project Inactive
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>