config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  resources :categories, only: [:index, :show], param: :slug

  resources :cart, only: [:index]
  resources :users, only: [:new, :create, :update, :edit]
  get "/lender_dashboard", to: "users#lender_dashboard"
  get "/borrower_dashboard", to: "users#borrower_dashboard"
  put '/become_borrower', to: "users#become_borrower"
  put '/become_lender', to: "users#become_lender"

  resources :lenders, only: [:new], param: :slug
  resources :borrowers, only: [:new], param: :slug

  get '/login', to: "session#new"
  post '/login', to: "session#create"
  delete '/logout', to: "session#destroy"
  post '/checkout', to: "loans#create"

  resources :borrower_projects, only: [:new, :create]
  resources :projects, only: [:index]

  namespace :admin do
    resources :dashboard, only: [:index, :show]
    resources :projects, only: [:update]
    resources :categories, only: [:index, :new, :create]
  end

  namespace :users, path: ":user", as: :user do
    resources :projects, only: [:show]
    resources :cart_projects, only: [:create, :new, :update, :destroy]
  end

  get '*unmatched_route', to: 'application#not_found'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :loans
  has_many :projects
  has_many :user_roles
  has_many :roles, through: :user_roles

  has_attached_file :image,
                    styles: {
                      thumb: '100x100>',
                      square: '200x200#',
                      medium: '300x300>'
                    },
                    default_url: "http://www.bankingtech.com/wp-content/blogs.dir/94/files/2013/11/India-women.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  validates :username, presence: true,
                       uniqueness: true
  validates :password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :slug, presence: true

  before_validation :set_slug

  # enum role: %w(default admin)

  def set_slug
    self.slug = full_name.parameterize
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    roles.exists?(name: "admin")
  end

  def borrower?
    roles.exists?(name: "borrower")
  end

  def lender?
    roles.exists?(name: "lender")
  end
end

app/controllers/users/cart_projects_controller.rb
class Users::CartProjectsController < ApplicationController
  def new
    @project = Project.find(params[:project])
  end

  def create
    project = Project.find(params[:cart_project][:project_id])
    amount = params[:cart_project][:amount].to_f

    if valid_amount?(amount, project)
      @cart.add_project(project.id, amount)
      session[:cart] = @cart.contents

      flash[:success] = "Added #{view_context.link_to "#{project.title}", user_project_path(user: project.user.slug, id: project.slug)} loan to your cart.".html_safe
      redirect_to cart_index_path
    else
      flash[:error] = "Please enter a valid amount"
      redirect_to new_user_cart_project_path(user: project.user.slug, project: project)
    end
  end

  def update
    project = Project.find(params[:id])
    amount = params[:project][:amount].to_f

    if valid_amount?(amount, project)
      @cart.update_loan(project.id, amount)
      session[:cart] = @cart.contents
      flash[:success] = "Successfully updated loan amount."
    else
      flash[:error] = "Sorry! That's not a valid loan amount."
    end
    redirect_to cart_index_path
  end

  def destroy
    project = Project.find(params[:id])
    @cart.remove_project(project.id)
    session[:cart] = @cart.contents
    flash[:success] = "Successfully removed #{view_context.link_to "#{project.title}", user_project_path(user: project.user.slug, id: project.slug)} loan from your cart.".html_safe
    redirect_to cart_index_path
  end
end

app/controllers/users/projects_controller.rb
class Users::ProjectsController < ApplicationController
  def show
    @project = Project.find_by_slug(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user = add_role(@user, params[:user][:role])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Logged in as #{@user.username}"
      redirect_to user_dashboard(current_user)
    else
      flash.now[:error] = "Something went wrong. Please try again."
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if !@user.update(user_params)
      flash[:error] = "Please enter your password"
      redirect_to edit_user_path
    else
      flash.notice = "Profile Updated!"
      redirect_to user_dashboard(current_user)
    end
  end

  def become_borrower
    current_user.roles << Role.find_by(name: "borrower")
    redirect_to borrower_dashboard_path
  end

  def become_lender
    current_user.roles << Role.find_by(name: "lender")
    redirect_to lender_dashboard_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :username,
                                 :password,
                                 :street_address,
                                 :city,
                                 :state,
                                 :zip,
                                 :bio,
                                 :image)
  end
end

app/views/users/borrower_dashboard.html.erb
<div id="profile-title" class="center">
  <div class="row">
    <div class="col s2 offset-s1">
      <a class="image-link"><img class="thumbnail circle" src="<%= current_user.image.url(:original) %>"></a>
    </div>
    <h2 class="left"><%= current_user.username %>'s Borrower Profile</h2>
  </div>
</div>
<div class="row">
  <div id="profile" class="col s8 offset-s2">
    <div>
      <p>
        <b>First name: </b><%= current_user.first_name %>
      </p>
      <p>
        <b>Last name: </b><%= current_user.last_name %>
      </p>
      <p>
        <b>Username: </b><%= current_user.username %>
      </p>
      <p>
        <b>Street address: </b><%= current_user.street_address %>
      </p>
      <p>
        <b>City: </b><%= current_user.city %>
      </p>
      <p>
        <b>State: </b><%= current_user.state %>
      </p>
      <p>
        <b>Zip: </b><%= current_user.zip %>
      </p>
      <p>
        <b>Bio: </b><%= current_user.bio %>
      </p>
      </p>
      <div id='user-<%= current_user.id %>-button' class="waves-effect waves-light btn-small custom-blue white-text ">
        <%= button_to "Edit Profile", edit_user_path(@user.id), method: :get %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <h3 class="center">Your Current Projects</h3>
  <ul class="col s10 offset-s2">
    <% current_user.projects.each do |project| %>
    <div class="row">
      <div class="col s2">
        <a class="image-link" href="<%= user_project_path(user: project.user.slug, id: project.slug) %>"><img class="thumbnail" src="<%= project.image.url(:original) %>"></a>
      </div>
      <div class="col s8">
        <li>Project Title: <%= project.title %></li>
        <li>Project Status: <%= project.status %></li>
        <li>Goal Amount: <%= number_to_currency(project.goal_amount) %></li>
        <li>Total Loans Received: <%= number_to_currency(project.total_loans_amount) %></li>
        <li>Percent Funded: <%= project.percent_funded %>%</li>
        <li>Description: <%= project.description %></li>
      </div>
    </div>
    <br></br>
    <% end %>
  </ul>

  <div class="center">
    <div class="create-project waves-effect waves-light btn custom-green">
      <%= button_to "Create A New Project", new_borrower_project_path, method: :get %>
    </div>
  </div>
</div>

<div class="center">
  <% if current_user.lender? %>
    <div id='user-<%= current_user.id %>-button' class="waves-effect waves-light btn custom-blue">
      <%= button_to "View Your Lender Profile", lender_dashboard_path, method: :get %>
    </div>
  <% else %>
    <div id='user-<%= @user.id %>-button' class="waves-effect waves-light btn custom-blue">
      <%= button_to "Become a Lender", become_lender_path(@user.id), method: :put %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user, :url => {:action => "update", :id => @user.id}) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :street_address %>
  <%= f.text_field :street_address %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip %>
  <%= f.text_field :zip %>

  <%= f.label :bio %>
  <%= f.text_field :bio %>

  <%= f.label :image %>
  <%= f.file_field :image, class: 'form-control' %><br><br>

  <%= f.submit "Update Profile" %>
<% end %>

app/views/users/lender_dashboard.html.erb
  <div id="profile-title" class="row center">
    <div class="col s2 offset-s1">
    <a class="image-link"><img class="thumbnail circle" src="<%= current_user.image.url(:original) %>"></a>
    </div>
    <h2 class="left"><%= current_user.username %>'s Lender Profile</h2>
  </div>

<div class="row">
  <div id="profile" class="col s8 offset-s2">
    <div>
      <p>
        <b>First name: </b><%= @user.first_name %>
      </p>
      <p>
        <b>Last name: </b><%= @user.last_name %>
      </p>
      <p>
        <b>Username: </b><%= @user.username %>
      </p>
      <p>
        <b>Street address: </b><%= current_user.street_address %>
      </p>
      <p>
        <b>City: </b><%= current_user.city %>
      </p>
      <p>
        <b>State: </b><%= current_user.state %>
      </p>
      <p>
        <b>Zip: </b><%= current_user.zip %>
      </p>
      <p>
        <b>Bio: </b><%= current_user.bio %>
      </p>
      <div id='user-<%= current_user.id %>-button' class="waves-effect waves-light btn-small custom-blue white-text">
        <%= button_to "Edit Profile", edit_user_path(current_user.id), method: :get %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <h3 class="center">Loans Made</h3>
  <ul class="col s8 offset-s2">
  <% current_user.loans.reverse.each do |loan| %>
    <div class="row">
      <li>
        <div class="col s4">
          <a class="image-link" href="<%= user_project_path(user: loan.project.user.slug, id: loan.project.slug) %>"><img id="project-image" class="thumbnail" src="<%= loan.project.image.url(:original) %>"></a>
        </div>
      </li>
      <li><b>Project Title: <%= loan.project.title %></b></li>
      <li>Loan Amount: <%= number_to_currency(loan.amount) %></li>
    </div>
    <br>
  <% end %>
  </ul>
</div>

<div class="center">
  <div class="waves-effect waves-light btn custom-green">
    <%= button_to "Lend", projects_path, method: :get %>
  </div>
</div>

<br>
  <div class="center">
    <% if current_user.borrower? %>
      <div id='user-<%= @user.id %>-button' class="waves-effect waves-light btn custom-blue">
        <%= button_to "View Your Borrower Profile", borrower_dashboard_path, method: :get %>
      </div>
    <% else %>
      <div id='user-<%= @user.id %>-button' class="waves-effect waves-light btn custom-blue">
        <%= button_to "Become a Borrower", become_borrower_path(current_user.id), method: :put %>
      </div>
    <% end %>
  </div>

app/views/users/new.html.erb
<h1 class="center-align">Choose an Account Type</h1>

<br>

<div class="account-types container">
  <%= button_to 'Create Lender Account', new_lender_path, method: :get, class: 'col s5 left waves-effect waves-light btn custom-green lender-btn' %>
  <%= button_to 'Create Borrower Account', new_borrower_path, method: :get, class: 'col s5 right waves-effect waves-light btn custom-blue borrower-btn' %>
</div>