config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  resources :categories, only: [:index, :show], param: :slug

  resources :cart, only: [:index]
  resources :users, only: [:new, :create, :update, :edit]
  get "/lender_dashboard", to: "users#lender_dashboard"
  get "/borrower_dashboard", to: "users#borrower_dashboard"
  put '/become_borrower', to: "users#become_borrower"
  put '/become_lender', to: "users#become_lender"

  resources :lenders, only: [:new], param: :slug
  resources :borrowers, only: [:new], param: :slug

  get '/login', to: "session#new"
  post '/login', to: "session#create"
  delete '/logout', to: "session#destroy"
  post '/checkout', to: "loans#create"

  resources :borrower_projects, only: [:new, :create]
  resources :projects, only: [:index]

  namespace :admin do
    resources :dashboard, only: [:index, :show]
    resources :projects, only: [:update]
    resources :categories, only: [:index, :new, :create]
  end

  namespace :users, path: ":user", as: :user do
    resources :projects, only: [:show]
    resources :cart_projects, only: [:create, :new, :update, :destroy]
  end

  get '*unmatched_route', to: 'application#not_found'
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true,
                    uniqueness: true
  validates :goal_amount, presence: true
  validates :slug, presence: true
  has_attached_file :image,
                    styles: {
                      thumb: '100x100>',
                      square: '200x200#',
                      medium: '300x300>'
                    },
                    default_url: "http://cliparts.co/cliparts/Lid/5A6/Lid5A66zT.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  belongs_to :category

  has_many :loans

  before_validation :set_slug

  scope :completed, -> { where(status: "Completed") }
  scope :pending, -> { where(status: "Pending") }
  scope :cancelled, -> { where(status: "Cancelled") }
  scope :active, -> { where(status: "Active") }

  def set_slug
    self.slug = title.parameterize
  end

  def total_loans_amount
    loans.map(&:amount).reduce(:+) || 0
  end

  def percent_funded
    (total_loans_amount / goal_amount * 100).round
  end

  def finished?
    if status.include?("Completed") || status.include?("Cancelled")
      true
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  def show
    @project = Project.find_by_slug(params[:id])
    @loans = @project.loans
  end

  def update
    project = Project.find(params[:id])
    project.update(:status => params[:status])
    redirect_to admin_dashboard_index_path
  end
end

app/controllers/borrowers/projects_controller.rb
class Borrowers::ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project successfully updated."
      current_user.projects << @project
      redirect_to borrower_dashboard_path
    else
      flash.now[:error] = "Something went wrong. Make sure you fill out all fields."
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:title,
                                    :goal_amount,
                                    :description,
                                    :image
                                    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.paginate(:page => params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/users/projects_controller.rb
class Users::ProjectsController < ApplicationController
  def show
    @project = Project.find_by_slug(params[:id])
  end
end

app/views/projects/_project.html.erb
<div class="card col s12">
  <div>
    <div class="col s4 top-margin-10">
      <a class="image-link" href="<%= user_project_path(user: project.user.slug, id: project.slug) %>"><img class="max-width" src="<%= project.image.url(:original) %>"></a>
    </div>
    <div class="col s7 offset-s1">
      <h5><%= project.title %></h5>
      <p><%= project.description %></p>
    </div>
    <div class="card-action col s7 offset-s1">
      <div class="center">
        <h5>Funding Goal: <%= number_to_currency(project.goal_amount) %></h5>
        <h5 class="custom-orange-text">Amount Loaned: <%= number_to_currency(project.total_loans_amount) %></h5>
        <h5 class="custom-green-text"><%= project.percent_funded %>% complete</h5>
      </div>
      <div class="center">
      <span id='<%= project.title %>-button' class="col s5 left waves-effect waves-light btn custom-blue">
        <%= button_to "Learn More", user_project_path(user: project.user.slug, id: project.slug), method: :get %>
      </span>
      <span id='<%= project.title%>-lend-button' >
        <%= link_to "Lend", new_user_cart_project_path(user: project.user.slug,
                                   project: project), class: "col s5 right waves-effect waves-light btn custom-blue white-text" %>
      </span>
    </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<h1 id="top">
  <%= "All Projects" %>
</h1>

<span id='categories-path-button' class="col s5 waves-effect waves-light btn custom-blue">
  <%= button_to "List of Project Categories", categories_path, method: :get %>
</span><br>

<div class="row">
  <div id="my-projects">
    <% @projects.each do |project| %>
      <%= render partial: "project", locals: { project: project } %>
    <% end %>
  </div>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @projects %>
</div>

<div class="center">
  <a class="waves-effect waves-light btn custom-blue" href="#primary-navigation">Back to top</a>
</div>
<br>

app/views/projects/index.js.erb
$('#my-projects').append('<%= j render partial: "project", collection: @projects %>');
<% if @projects.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @projects %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>