config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  resources :categories, only: [:index, :show], param: :slug

  resources :cart, only: [:index]
  resources :users, only: [:new, :create, :update, :edit]
  get "/lender_dashboard", to: "users#lender_dashboard"
  get "/borrower_dashboard", to: "users#borrower_dashboard"
  put '/become_borrower', to: "users#become_borrower"
  put '/become_lender', to: "users#become_lender"

  resources :lenders, only: [:new], param: :slug
  resources :borrowers, only: [:new], param: :slug

  get '/login', to: "session#new"
  post '/login', to: "session#create"
  delete '/logout', to: "session#destroy"
  post '/checkout', to: "loans#create"

  resources :borrower_projects, only: [:new, :create]
  resources :projects, only: [:index]

  namespace :admin do
    resources :dashboard, only: [:index, :show]
    resources :projects, only: [:update]
    resources :categories, only: [:index, :new, :create]
  end

  namespace :users, path: ":user", as: :user do
    resources :projects, only: [:show]
    resources :cart_projects, only: [:create, :new, :update, :destroy]
  end

  get '*unmatched_route', to: 'application#not_found'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true,
                    uniqueness: true

  has_many :projects

  before_save :to_slug

  def to_slug
    self.slug = title.parameterize
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "#{@category.title} created!"
      redirect_to admin_categories_path
    else
      flash[:error] = "Something went wrong. Please enter a title."
      redirect_to new_admin_category_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by_slug(params[:slug])
  end
end

app/views/categories/index.html.erb
<h1>Active Projects by State in India</h1>

<div class="collection">
  <% @categories.each do |category| %>
    <div class="collection-item">
      <%= link_to category.title, category_path(category.slug) %>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.title %> Projects</h1>

<div id='project' class="row">
  <% @category.projects.each do |project| %>
      <div class="card col s12">
        <div>
          <div class="col s4">
            <a class="image-link" href="<%= user_project_path(user: project.user.slug, id: project.slug) %>"><img class="max-width" src="<%= project.image.url(:original) %>"></a>
          </div>
          <div class="col s7 offset-s1">
            <h5><%= project.title %></h5>
            <p><%= project.description %></p>
          </div>
          <div class="card-action col s7 offset-s1">
            <div class="center">
              <h5>Funding Goal: <%= number_to_currency(project.goal_amount) %></h5>
              <h5 class="custom-orange-text">Amount Loaned: <%= number_to_currency(project.total_loans_amount) %></h5>
              <h5 class="custom-green-text"><%= project.percent_funded %>% complete</h5>
            </div>
            <div class="center">
            <span id='<%= project.title %>-button' class="col s5 left waves-effect waves-light btn custom-blue">
              <%= button_to "Learn More", user_project_path(user: project.user.slug, id: project.slug), method: :get %>
            </span>
            <span id='<%= project.title%>-lend-button' >
              <%= link_to "Lend", new_user_cart_project_path(user: project.user.slug,
                                         project: project), class: "col s5 right waves-effect waves-light btn custom-blue white-text" %>
            </span>
          </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="center">
    <a class="waves-effect waves-light btn custom-blue" href="#primary-navigation">Back to top</a>
  </div>
  <br>